[tool.poetry]
name = "hello-python"
version = "0.1.0"
description = "Learn Python"
authors = ["Vu Hoang Viet"]
license = "Apache License 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
