name: dev-ci-cd
on:
  push:
    branches:
      - develop
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  PREFIX: dev

jobs:
  builddocker:
    runs-on: ubuntu-latest                           
    environment: CI
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      shortsha: ${{ steps.short_sha.outputs.shortsha }}
    steps:
      - uses: actions/checkout@v4
      - name: Set Short SHA
        id: short_sha
        run: | 
          shortsha=$(git rev-parse --short ${{ github.sha }})
          echo "shortsha=${shortsha}">> "$GITHUB_OUTPUT"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,enable=true,priority=100,prefix=${{ env.PREFIX }}-,suffix=,format=short   
      - run : echo "SHA "${{ steps.short_sha.outputs.shortsha }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.VVU_GITHUB_TOKEN }}      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy-to-environment:
    runs-on: ubuntu-latest
    environment: CI
    needs: builddocker
    steps:
      - name: Check version to update yaml
        run: echo "Version to update yaml is ${{needs.builddocker.outputs.tags}}"
      - name: Update yaml and push
        uses: rusowyler/github-action-yaml-update-and-push@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.VVU_GITHUB_TOKEN }}
        with:
          yq-version: "v4.20.2"
          yaml-file: infra/hello-application.yaml
          yaml-path: .Mappings.Applications.HelloPython.Version
          yaml-value: ${{ env.PREFIX }}-${{needs.builddocker.outputs.shortsha}}
          repository-username: ${{ github.repository_owner }}
          repository-name: aws-cf-infra-template
          user-name: ${{ github.repository_owner }}
          branch: develop
          commit-message: "Update hello-python version to ${{ env.PREFIX }}-${{needs.builddocker.outputs.shortsha}}"
